# Generated by Django 4.1 on 2022-11-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0006_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="rating",),
    ]
