# Generated by Django 4.1 on 2022-11-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0007_remove_product_rating"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("image_url", models.CharField(max_length=200)),
                ("href", models.CharField(max_length=200)),
            ],
        ),
    ]
