# Generated by Django 4.1 on 2022-11-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0008_ad"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad", name="href", field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="ad", name="image_url", field=models.CharField(max_length=500),
        ),
    ]
