# Generated by Django 4.1 on 2022-11-16 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0009_alter_ad_href_alter_ad_image_url"),
    ]

    operations = [
        migrations.AlterField(model_name="ad", name="href", field=models.TextField(),),
    ]
