# Generated by Django 4.1 on 2022-11-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0010_alter_ad_href"),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
            ],
        ),
    ]
