# Generated by Django 4.1 on 2022-11-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0011_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255, unique=True)),
            ],
        ),
    ]
