# Generated by Django 4.1 on 2022-12-09 14:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0012_newsletter"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="temp_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Price"
            ),
        ),
    ]
