# Generated by Django 4.1 on 2022-12-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0015_rename_temp_id_order_id"),
    ]

    operations = [
        migrations.RemoveField(model_name="orderitem", name="order",),
    ]
